# code: language=Ansible insertSpaces=true tabSize=2


- name: Lock Ansible user account password
  user:
    name: "{{ system_ansible_user_name }}"
    state: present
    password_lock: yes
  tags:
    - never
    - setup


- name: Unlock Ansible user account password
  user:
    name: "{{ system_ansible_user_name }}"
    state: present
    password_lock: no
  tags:
    - never
    - teardown
    - remove
